version: 2.1

jobs:
  one:
    docker:
      - image: cimg/ruby:2.6.8
    steps:
      - checkout
      - run:
          name: first hellow world
          command: echo "my first command by atharva"
      - run:
          name: sleep
          command: sleep 25
          
  two:
    docker:
      - image: cimg/ruby:3.0.2
    steps:
      - checkout
      - run:
          name: second hello
          command: echo "hello world"
      - run: 
          name: sleep
          command: sleep 15

workflows:
  one_and_two:
    jobs:
      - one
      - two
